manifest:
  defaults:
    revision: v0.3       # ZMK バージョンに合わせる
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: caksoylar       # 新しいリモート追加
      url-base: https://github.com/caksoylar
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    - name: zmk-rgbled-widget   # 新しいプロジェクト追加
      remote: caksoylar
      revision: v0.3            # ZMK バージョンに合わせる
  self:
    path: config
