manifest:
  defaults:
    revision: v0.3   # ← v0.3 から変更（最新版を使う）

  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: caksoylar
      url-base: https://github.com/caksoylar

  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml

    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: v0.3   # ← v0.3 → main に変更

  self:
    path: config
